#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
  CREATE USER ${NEXTCLOUD_DB_USER} WITH PASSWORD '${NEXTCLOUD_DB_PASSWORD}';
  CREATE DATABASE nextcloud OWNER ${NEXTCLOUD_DB_USER};

  CREATE USER ${IMMICH_DB_USER} WITH PASSWORD '${IMMICH_DB_PASSWORD}';
  CREATE DATABASE immich OWNER ${IMMICH_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username postgres --dbname immich <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS vector;
  CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
EOSQL
