# Homepage settings
# https://gethomepage.dev/configs/settings/

title: Home Server

# Allow all hosts (needed for Tailscale and local network)
allowedHosts:
  - "*"

background:
  opacity: 50

theme: dark
color: slate

layout:
  Uso Quotidiano:
    style: row
    columns: 5
  AI:
    style: row
    columns: 3
  Database:
    style: row
    columns: 5
  Monitoring:
    style: row
    columns: 6
  Networking:
    style: row
    columns: 2
